### ISSUE TITLE
Where's your SVG

### ISSUE THREAD

**Issue by LovelyBuggies** [yuqingc/yuqingc.github.io#2]
Hello, I am here from Mainroad Hugo theme repo. Ur blog is amazing. Actually, I am curious about where is your blibli svg and how you can get it. Thanks a lot!

**Comment by yuqingc** [comment]
@LovelyBuggies https://www.iconfont.cn/

**Comment by LovelyBuggies** [comment]
Thanks, but I mean do you have a folder named like `svg` in `partials` (I see you put your svg file directly into the index.html). By the way, how do you start your hugo server (I tried `hugo server -D`, but this doesn't work)?

**Comment by yuqingc** [comment]
@LovelyBuggies This repo is the output dir after compiling. Settings for custom links with SVG icons can be referred here (https://github.com/Vimux/Mainroad#social-widget-custom-links) 

> ### Social Widget: custom links
>
> **Mainroad** contains built-in social links in the social widget. In addition, you can also set custom social links by adding `Params.widgets.social.custom` to your `config.toml`. Here is an example.
>
> ```toml
> [[Params.widgets.social.custom]]
>   title = "Youtube"
>   url = "https://youtube.com/user/username"
>   icon = "youtube.svg"
> ```
>
> **Note:** You need to put your icon file in `layouts/partials` directory under your project's root if you want to display an icon of your social link. The `icon` filed, which is optional, should be a path relative to `layouts/partials`.
>
> **Note:** *Only* SVG files are supported to be used as custom social icons in the current version. If you use any files of another format, PNG for example, a compile error will be raised by Hugo.
>
> **Note:** Not every SVG icon can be used. For better results, it should be one-color SVG file with a special class attribute `{{ with .class }}{{ . }} {{ end }}` and 24x24 size. At a minimum, custom SVG icon needs these attributes:
>
> ```html
> <svg class="{{ with .class }}{{ . }} {{ end }} icon" width="24" height="24">...</svg>
> ```
